version: '3'
services:
  nginx.chitoge.com:
    image: webapp
    build:
      context: ./webapp
      dockerfile: Dockerfile
    expose:
      - 80
    ports:
      - "80:80"
    depends_on:
      - "jira.chitoge.com"

  jira.chitoge.com:
    image: jira-lab
    build:
      context: ./jira
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - "8081:8080"
